languageCode = "en"
languageName = "English"
weight = 1
title = "CurrySIN's Station"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/currysin_logo_transparent.png"
  description = "Here for ME, Here for YOU"

[author]
  name = "Curry SIN"
  image = "img/currysin_logo.png"
  headline = "Here for ME, Here for YOU"
  bio = "Here for ME, Here for YOU"
  links = [
    { x-twitter = "https://twitter.com/sin_curry" },
    { github = "https://github.com/currysinhk" },
    { youtube = "https://www.youtube.com/channel/UCSTOmrWyUF_PW_20d1ILkFA" },
  ]