baseURL = "https://currysinhk.github.io/blog/"
languageCode = "en-us"
title = "Curry Sin Space"
theme = "origin-hugo-theme"
tag = "tags"
series = "series"
category = "categories"
enbaleEmoji = "true"
timeZone = "Hongkong"