baseURL = "https://currysinhk.github.io/"
languageCode = "zh"
title = "Curry Sin的雜物房間"
theme = "origin-hugo-theme"
copyright = "© 2022, Curry Sin; Theme, Andrey Parfenov"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
enbaleEmoji = "true"
# timeZone = "Hongkong"
# paginate = 7
# canonifyurls = true

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"
  
[params]
  description = "simple hugo theme"
  featured = true
  cssonly = false

  [params.socials]
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = ""
    gitlab = ""
    linkedin = ""
    slack = ""
    stackoverflow = ""
    medium= ""

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

# [permalinks]
#   posts = '/:year/:month/:title/'
